from __future__ import annotations

import re

ADAPTIVE_RETRY_MIN_WORDS = 20
SCHEMA_FALLBACK_MIN_GAIN = 3

# ─── Removal constants (ported from defuddle) ────────────────────────

MIN_IMAGE_SIZE = 33

# Tailwind default palette, used to resolve CSS variables and utility
# classes on inline SVGs once the page's stylesheets are gone.
# Ported from defuddle constants.ts TAILWIND_COLORS / TAILWIND_SPECIAL.
# fmt: off
TAILWIND_COLORS: dict[str, dict[str, str]] = {
    "slate":   {"50": "#f8fafc", "100": "#f1f5f9", "200": "#e2e8f0", "300": "#cbd5e1", "400": "#94a3b8", "500": "#64748b", "600": "#475569", "700": "#334155", "800": "#1e293b", "900": "#0f172a", "950": "#020617"},  # noqa: E501
    "gray":    {"50": "#f9fafb", "100": "#f3f4f6", "200": "#e5e7eb", "300": "#d1d5db", "400": "#9ca3af", "500": "#6b7280", "600": "#4b5563", "700": "#374151", "800": "#1f2937", "900": "#111827", "950": "#030712"},  # noqa: E501
    "zinc":    {"50": "#fafafa", "100": "#f4f4f5", "200": "#e4e4e7", "300": "#d4d4d8", "400": "#a1a1aa", "500": "#71717a", "600": "#52525b", "700": "#3f3f46", "800": "#27272a", "900": "#18181b", "950": "#09090b"},  # noqa: E501
    "neutral": {"50": "#fafafa", "100": "#f5f5f5", "200": "#e5e5e5", "300": "#d4d4d4", "400": "#a3a3a3", "500": "#737373", "600": "#525252", "700": "#404040", "800": "#262626", "900": "#171717", "950": "#0a0a0a"},  # noqa: E501
    "stone":   {"50": "#fafaf9", "100": "#f5f5f4", "200": "#e7e5e4", "300": "#d6d3d1", "400": "#a8a29e", "500": "#78716c", "600": "#57534e", "700": "#44403c", "800": "#292524", "900": "#1c1917", "950": "#0c0a09"},  # noqa: E501
    "red":     {"50": "#fef2f2", "100": "#fee2e2", "200": "#fecaca", "300": "#fca5a5", "400": "#f87171", "500": "#ef4444", "600": "#dc2626", "700": "#b91c1c", "800": "#991b1b", "900": "#7f1d1d", "950": "#450a0a"},  # noqa: E501
    "orange":  {"50": "#fff7ed", "100": "#ffedd5", "200": "#fed7aa", "300": "#fdba74", "400": "#fb923c", "500": "#f97316", "600": "#ea580c", "700": "#c2410c", "800": "#9a3412", "900": "#7c2d12", "950": "#431407"},  # noqa: E501
    "amber":   {"50": "#fffbeb", "100": "#fef3c7", "200": "#fde68a", "300": "#fcd34d", "400": "#fbbf24", "500": "#f59e0b", "600": "#d97706", "700": "#b45309", "800": "#92400e", "900": "#78350f", "950": "#451a03"},  # noqa: E501
    "yellow":  {"50": "#fefce8", "100": "#fef9c3", "200": "#fef08a", "300": "#fde047", "400": "#facc15", "500": "#eab308", "600": "#ca8a04", "700": "#a16207", "800": "#854d0e", "900": "#713f12", "950": "#422006"},  # noqa: E501
    "lime":    {"50": "#f7fee7", "100": "#ecfccb", "200": "#d9f99d", "300": "#bef264", "400": "#a3e635", "500": "#84cc16", "600": "#65a30d", "700": "#4d7c0f", "800": "#3f6212", "900": "#365314", "950": "#1a2e05"},  # noqa: E501
    "green":   {"50": "#f0fdf4", "100": "#dcfce7", "200": "#bbf7d0", "300": "#86efac", "400": "#4ade80", "500": "#22c55e", "600": "#16a34a", "700": "#15803d", "800": "#166534", "900": "#14532d", "950": "#052e16"},  # noqa: E501
    "emerald": {"50": "#ecfdf5", "100": "#d1fae5", "200": "#a7f3d0", "300": "#6ee7b7", "400": "#34d399", "500": "#10b981", "600": "#059669", "700": "#047857", "800": "#065f46", "900": "#064e3b", "950": "#022c22"},  # noqa: E501
    "teal":    {"50": "#f0fdfa", "100": "#ccfbf1", "200": "#99f6e4", "300": "#5eead4", "400": "#2dd4bf", "500": "#14b8a6", "600": "#0d9488", "700": "#0f766e", "800": "#115e59", "900": "#134e4a", "950": "#042f2e"},  # noqa: E501
    "cyan":    {"50": "#ecfeff", "100": "#cffafe", "200": "#a5f3fc", "300": "#67e8f9", "400": "#22d3ee", "500": "#06b6d4", "600": "#0891b2", "700": "#0e7490", "800": "#155e75", "900": "#164e63", "950": "#083344"},  # noqa: E501
    "sky":     {"50": "#f0f9ff", "100": "#e0f2fe", "200": "#bae6fd", "300": "#7dd3fc", "400": "#38bdf8", "500": "#0ea5e9", "600": "#0284c7", "700": "#0369a1", "800": "#075985", "900": "#0c4a6e", "950": "#082f49"},  # noqa: E501
    "blue":    {"50": "#eff6ff", "100": "#dbeafe", "200": "#bfdbfe", "300": "#93c5fd", "400": "#60a5fa", "500": "#3b82f6", "600": "#2563eb", "700": "#1d4ed8", "800": "#1e40af", "900": "#1e3a8a", "950": "#172554"},  # noqa: E501
    "indigo":  {"50": "#eef2ff", "100": "#e0e7ff", "200": "#c7d2fe", "300": "#a5b4fc", "400": "#818cf8", "500": "#6366f1", "600": "#4f46e5", "700": "#4338ca", "800": "#3730a3", "900": "#312e81", "950": "#1e1b4b"},  # noqa: E501
    "violet":  {"50": "#f5f3ff", "100": "#ede9fe", "200": "#ddd6fe", "300": "#c4b5fd", "400": "#a78bfa", "500": "#8b5cf6", "600": "#7c3aed", "700": "#6d28d9", "800": "#5b21b6", "900": "#4c1d95", "950": "#2e1065"},  # noqa: E501
    "purple":  {"50": "#faf5ff", "100": "#f3e8ff", "200": "#e9d5ff", "300": "#d8b4fe", "400": "#c084fc", "500": "#a855f7", "600": "#9333ea", "700": "#7e22ce", "800": "#6b21a8", "900": "#581c87", "950": "#3b0764"},  # noqa: E501
    "fuchsia": {"50": "#fdf4ff", "100": "#fae8ff", "200": "#f5d0fe", "300": "#f0abfc", "400": "#e879f9", "500": "#d946ef", "600": "#c026d3", "700": "#a21caf", "800": "#86198f", "900": "#701a75", "950": "#4a044e"},  # noqa: E501
    "pink":    {"50": "#fdf2f8", "100": "#fce7f3", "200": "#fbcfe8", "300": "#f9a8d4", "400": "#f472b6", "500": "#ec4899", "600": "#db2777", "700": "#be185d", "800": "#9d174d", "900": "#831843", "950": "#500724"},  # noqa: E501
    "rose":    {"50": "#fff1f2", "100": "#ffe4e6", "200": "#fecdd3", "300": "#fda4af", "400": "#fb7185", "500": "#f43f5e", "600": "#e11d48", "700": "#be123c", "800": "#9f1239", "900": "#881337", "950": "#4c0519"},  # noqa: E501
}
# fmt: on
TAILWIND_SPECIAL: dict[str, str] = {
    "black": "#000",
    "white": "#fff",
    "transparent": "transparent",
    "current": "currentColor",
}

# Hidden-element selectors removed in the exact-selector phase.  The
# skip variant (no :not() guards) is used to *detect* hidden subtrees —
# closest-ancestor checks and the hidden-content retry — while the
# removal variant preserves math/svg and paywalled text (sites like
# Future PLC gate paragraphs with aria-hidden + class="paywall").
# Ported from defuddle constants.ts HIDDEN_EXACT_(SKIP_)SELECTORS.
HIDDEN_EXACT_SKIP_SELECTORS: list[str] = [
    "[hidden]",
    '[aria-hidden="true"]',
    ".hidden",
    ".invisible",
]
# Deviation from upstream: the aria-hidden guard also covers bare <math>
# elements and KaTeX/MathJax wrappers case-insensitively — markitai keeps
# LaTeX sources that sites mark aria-hidden for accessibility (see
# tests/unit/webextract/test_review_fixes.py TestMathProtection).
HIDDEN_EXACT_SELECTORS: list[str] = [
    '[aria-hidden="true"]:not(math):not([class*="math" i])'
    ':not([class*="katex" i]):not(svg):not([class*="paywall"])'
    if s == '[aria-hidden="true"]'
    else s
    for s in HIDDEN_EXACT_SKIP_SELECTORS
]
HIDDEN_EXACT_SELECTOR: str = ", ".join(HIDDEN_EXACT_SELECTORS)
HIDDEN_EXACT_SKIP_SELECTOR: str = ", ".join(HIDDEN_EXACT_SKIP_SELECTORS)

# Exact CSS selectors for elements to remove.
# These are high-confidence removals — nav, footer, ads, forms, etc.
EXACT_SELECTORS: list[str] = [
    # scripts, styles
    "noscript",
    "style",
    "meta",
    "link",
    # ads
    ".ad",
    "[role='banner']",
    ".promo",
    ".Promo",
    "#barrier-page",
    # NOTE: .alert excluded — handled by callout normalization in standardize
    # comments
    "#comments",
    "#comment",
    # cover images
    "div[class*='cover-']",
    "div[id*='cover-']",
    # header, nav
    "header",
    ".header",
    "#header",
    "#Header",
    "#banner",
    "#Banner",
    "nav",
    ".navigation",
    "#navigation",
    "[role='navigation']",
    "[role='dialog']",
    "[role='complementary']",
    ".menu",
    "#siteSub",
    ".previous",
    # metadata
    ".author",
    ".Author",
    "#categories",
    ".contributor",
    ".date",
    "#date",
    "[data-date]",
    ".entry-meta",
    ".meta",
    ".tags",
    "#tags",
    "[rel='tag']",
    ".toc",
    ".Toc",
    "#toc",
    ".headline",
    "#headline",
    "#title",
    "#Title",
    "#articleTag",
    "[href*='/tag/']",
    "[href*='/tags/']",
    "[href*='/author/']",
    "[href*='/author?']",
    "[href$='/author']",
    "a[href*='copyright.com']",
    "a[href*='google.com/preferences']",
    "[href*='#toc']",
    "[href='#top']",
    "[href='#Top']",
    "[href='#page-header']",
    "[href='#content']",
    "[href='#site-content']",
    "[href='#main-content']",
    "[src*='author']",
    # footer
    "footer",
    # inputs, forms
    ".aside",
    "aside:not([class*='callout'])",
    "button",
    "canvas",
    "dialog",
    "fieldset",
    "form",
    "input:not([type='checkbox'])",
    "label",
    "option",
    "select",
    "[role='listbox']",
    "[role='option']",
    "textarea",
    # hidden (aria-hidden guarded to preserve math/svg/paywalled text)
    *HIDDEN_EXACT_SELECTORS,
    # iframes (except video embeds)
    "instaread-player",
    # logos
    "#logo",
    "#Logo",
    # newsletter
    "#newsletter",
    "#Newsletter",
    ".subscribe",
    # print
    ".noprint",
    # footnote citations
    "[class*='clickable-icon']",
    # link lists
    "[data-container*='most-viewed']",
    # sidebar
    ".sidebar",
    ".Sidebar",
    "#sidebar",
    "#Sidebar",
    "#side-bar",
    "#sitesub",
    # skip links
    "[data-link-name*='skip']",
    "[aria-label*='skip']",
    # dismiss/close buttons
    "[aria-label='Dismiss' i]",
    "[aria-label='Close' i]",
    # icon SVGs (Font Awesome)
    "svg[data-icon]",
    # other
    ".copyright",
    "#copyright",
    ".licensebox",
    "#page-info",
    "#rss",
    "#feed",
    ".gutter",
    "#primaryaudio",
    "#NYT_ABOVE_MAIN_CONTENT_REGION",
    "table.infobox",
    ".gh-header-sticky",
]

# Pre-joined CSS selector for single-query removal (performance optimization).
EXACT_SELECTORS_JOINED: str = ", ".join(EXACT_SELECTORS)

# Partial selector patterns tested against class/id/data-test* attributes.
# Case-insensitive substring matches.
PARTIAL_SELECTOR_PATTERNS: list[str] = [
    "a-statement",
    "access-wall",
    "activitypub",
    "actioncall",
    "addcomment",
    "addtoany",
    "advert",
    "adlayout",
    "ad-tldr",
    "ad-placement",
    "ads-container",
    "_ad_",
    "AdBlock_",
    "AdUnit",
    "after_content",
    "after_main_article",
    "afterpost",
    # NOTE: "-alert-" removed — it false-positives on "markdown-alert" (GitHub
    # callout/admonition classes).  Cookie/banner alerts are covered by
    # "cookie", "-banner-", and the exact ".alert" selector was already
    # excluded in EXACT_SELECTORS for the same reason.
    "alert-box",
    "_archive",
    "around-the-web",
    "article-author",
    "article-badges",
    "article-banner",
    "article-bottom",
    "article-category",
    "article-card",
    "article-citation",
    "article_date",
    "article-date",
    "article_header",
    "article-header",
    "article__header",
    "article__hero",
    "article__info",
    "article-info",
    "article-meta",
    "article_meta",
    "article__meta",
    "article-subject",
    "article-snippet",
    "article-separator",
    "article--share",
    "article--topics",
    "articletags",
    "article-tags",
    "article_tags",
    "articletitle",
    "article-title",
    "article_title",
    "articletopics",
    "article-topics",
    "article-actions",
    "article--lede",
    "articlewell",
    "associated-people",
    "audio-card",
    "author-bio",
    "author-box",
    "author-info",
    "author_info",
    "author-mini-bio",
    "author-name",
    "author-publish-info",
    "authored-by",
    "avatar",
    "back-to-top",
    "backlink_container",
    "backlinks-section",
    "bio-block",
    "biobox",
    "blog-pager",
    "bookmark-",
    "-bookmark",
    "bottominfo",
    "bottomnav",
    "bottom-of-article",
    "bottom-wrapper",
    "brand-bar",
    "bcrumb",
    "breadcrumb",
    "brdcrumb",
    "button-wrapper",
    "buttons-container",
    "btn-",
    "-btn",
    "byline",
    "captcha",
    "card-text",
    "card-media",
    "card-post",
    "carouselcontainer",
    "carousel-container",
    "cat_header",
    "catlinks",
    "_categories",
    "card-author",
    "card-content",
    "chapter-list",
    "collections",
    "comments",
    "-comment",
    "commentbox",
    "comment-button",
    "commentcomp",
    "comment-content",
    "comment-count",
    "comment-form",
    "comment-number",
    "comment-respond",
    "comment-thread",
    "comment-wrap",
    "complementary",
    "consent",
    "contact-",
    "content-card",
    "content-topics",
    "contentpromo",
    "context-bar",
    "context-widget",
    "core-collateral",
    "cover-image",
    "cover-photo",
    "cover-wrap",
    "created-date",
    "creative-commons_",
    "c-subscribe",
    "_cta",
    "-cta",
    "cta-",
    "cta_",
    "current-issue",
    "custom-list-number",
    "dateline",
    "dateheader",
    "date-header",
    "date-pub",
    "disclaimer",
    "disclosure",
    "discussion",
    "discuss_",
    "-dismiss",
    "disqus",
    "donate",
    "donation",
    "dropdown",
    "element-invisible",
    "emailsignup",
    "emoji-bar",
    "engagement-widget",
    "enhancement-",
    "entry-author-info",
    "entry-categories",
    "entry-date",
    "entry-title",
    "entry-utility",
    "-error",
    "error-",
    "eyebrow",
    "expand-reduce",
    "external-anchor",
    "externallinkembedwrapper",
    "extra-services",
    "extra-title",
    "facebook",
    "fancy-box",
    "favorite",
    "featured-content",
    "feature_feed",
    "feedback",
    "feed-links",
    "field-site-sections",
    "fixheader",
    "floating-vid",
    "follower",
    "footer",
    "footnote-back",
    "footnoteback",
    "form-group",
    "for-you",
    "frontmatter",
    "further-reading",
    "fullbleedheader",
    "gallery-count",
    "gated-",
    "gh-feed",
    "gist-meta",
    "goog-",
    "graph-view",
    "hamburger",
    "header_logo",
    "header-logo",
    "header-pattern",
    "hero-list",
    "hide-for-print",
    "hide-print",
    "hide-when-no-script",
    "hidden-print",
    "hidden-sidenote",
    "hidden-accessibility",
    "infoline",
    "inline-topic",
    "interlude",
    "interaction",
    "intro-date",
    "invisible",
    "jp-relatedposts",
    "jswarning",
    "js-warning",
    "jumplink",
    "jumpto",
    "jump-to-",
    "js-skip-to-content",
    "keepreading",
    "keep-reading",
    "keep_reading",
    "keyword_wrap",
    "kicker",
    "labstab",
    "-labels",
    "language-name",
    "lastupdated",
    "latest-content",
    "-ledes-",
    "-license",
    "license-",
    "lightbox-popup",
    "like-button",
    "link-box",
    "links-grid",
    "links-title",
    "listing-dynamic-terms",
    "list-tags",
    "loading",
    "logo_container",
    "ltx_role_refnum",
    "ltx_tag_bibitem",
    "ltx_error",
    "masthead",
    "marketing",
    "media-inquiry",
    "-menu",
    "menu-",
    "metadata",
    "meta-date",
    "meta-row",
    "might-like",
    "minibio",
    "more-about",
    "mod-paywall",
    "_modal",
    "-modal",
    "more-",
    "morenews",
    "morestories",
    "more_wrapper",
    "most-read",
    "move-helper",
    "mw-editsection",
    "mw-cite-backlink",
    "mw-indicators",
    "mw-jump-link",
    "nav-",
    "nav_",
    "navigation-post",
    "next-",
    "newsgallery",
    "news-story-title",
    "newsletter_",
    "newsletterbanner",
    "newslettercontainer",
    "newsletter-form",
    "newsletter-signup",
    "newslettersignup",
    "newsletterwidget",
    "newsletterwrapper",
    "not-found",
    "notessection",
    "nomobile",
    "noprint",
    "open-slideshow",
    "originally-published",
    "other-blogs",
    "outline-view",
    "pagehead",
    "page-header",
    "page-title",
    "paywall_message",
    "-partners",
    "permission-",
    "plea",
    "popular",
    "popup_links",
    "pop_stories",
    "pop-up",
    "post-author",
    "post-bottom",
    "post__category",
    "postcomment",
    "postdate",
    "post-date",
    "post_date",
    "post-details",
    "post-feeds",
    "postinfo",
    "post-info",
    "post_info",
    "post-inline-date",
    "post-links",
    "postlist",
    "post_list",
    "post_meta",
    "post-meta",
    "postmeta",
    "post_more",
    "postnavi",
    "post-navigation",
    "postpath",
    "post-preview",
    "postsnippet",
    "post_snippet",
    "post-snippet",
    "post-subject",
    "posttax",
    "post-tax",
    "post_tax",
    "posttag",
    "post_tag",
    "post-tag",
    "post_time",
    "posttitle",
    "post-title",
    "post_title",
    "post__title",
    "post-ufi-button",
    "prev-post",
    "prevnext",
    "prev_next",
    "prev-next",
    "previousnext",
    "press-inquiries",
    "print-none",
    "print-header",
    "print:hidden",
    "privacy-notice",
    "privacy-settings",
    "profile",
    "promo_article",
    "promo-bar",
    "promo-box",
    "pubdate",
    "pub_date",
    "pub-date",
    "publish_date",
    "publish-date",
    "publication-date",
    "publicationName",
    "qr-code",
    "qr_code",
    "quick_up",
    "_rail",
    "ratingssection",
    "read_also",
    "readmore",
    "read-next",
    "read_next",
    "read_time",
    "read-time",
    "reading_time",
    "reading-time",
    "reading-list",
    "recent-",
    "recent-articles",
    "recentpost",
    "recent_post",
    "recent-post",
    "recommend",
    "redirectedfrom",
    "recirc",
    "register",
    "related",
    "relevant",
    "reversefootnote",
    "robots-nocontent",
    "_rss",
    "rss-link",
    "screen-reader-text",
    "scroll_to",
    "scroll-to",
    "_search",
    "-search",
    "section-nav",
    "series-banner",
    "share-box",
    "sharedaddy",
    "share-icons",
    "sharelinks",
    "share-post",
    "share-print",
    "share-section",
    "shariff-",
    "show-for-print",
    "sidebartitle",
    "sidebar-content",
    "sidebar-wrapper",
    "sideitems",
    "sidebar-author",
    "sidebar-item",
    "side-box",
    "side-logo",
    "sign-in-gate",
    "similar-",
    "similar_",
    "similars-",
    "site-index",
    "site-header",
    "siteheader",
    "site-logo",
    "site-name",
    "site-wordpress",
    "skip-content",
    "skip-to-content",
    "skip-link",
    "c-skip-link",
    "_skip-link",
    "-slider",
    "slug-wrap",
    "social-author",
    "social-shar",
    "social-date",
    "speechify-ignore",
    "speedbump",
    "sponsor",
    "springercitation",
    "sr-only",
    "_stats",
    "story-date",
    "story-navigation",
    "storyreadtime",
    "storysmall",
    "storypublishdate",
    "subject-label",
    "subhead",
    "submenu",
    "-subscribe-",
    "subscriber-drive",
    "subscription-",
    "_tags",
    "tags__item",
    "tag_list",
    "taxonomy",
    "table-of-contents",
    "tabs-",
    "terminaltout",
    "time-rubric",
    "timestamp",
    "time-read",
    "time-to-read",
    "tip_off",
    "tiptout",
    "-tout-",
    "toc-container",
    "toggle-caption",
    "tooltip-content",
    "topbar",
    "topic-authors",
    "topic-footer",
    "topic-list",
    "topic-subnav",
    "top-wrapper",
    "tree-item",
    "trending",
    "trust-feat",
    "trust-badge",
    "trust-project",
    "twitter",
    "u-hide",
    "upsell",
    "viewbottom",
    "yarpp-related",
    "visually-hidden",
    "welcomebox",
    "widget_pages",
]

# Pre-compiled regex for partial selector matching
PARTIAL_SELECTOR_REGEX: re.Pattern[str] = re.compile(
    "|".join(re.escape(p) for p in PARTIAL_SELECTOR_PATTERNS),
    re.IGNORECASE,
)

# Anchored variant: the whole value must equal one selector token outright.
# Used for delimiter-less ids, which are usually content anchors made of
# concatenated heading words (e.g. "loopsandfeedback") — substring matching
# would wrongly strip them (hitting "feedback").
PARTIAL_SELECTOR_ANCHORED_REGEX: re.Pattern[str] = re.compile(
    "^(?:" + "|".join(re.escape(p) for p in PARTIAL_SELECTOR_PATTERNS) + ")$",
    re.IGNORECASE,
)

# Attributes to check for partial selector matches
TEST_ATTRIBUTES: tuple[str, ...] = (
    "class",
    "id",
    "data-test",
    "data-testid",
    "data-test-id",
    "data-qa",
    "data-cy",
)

# Navigation indicator patterns for scoring
NAVIGATION_INDICATORS: list[str] = [
    "advertisement",
    "all rights reserved",
    "banner",
    "cookie",
    "comments",
    "copyright",
    "follow me",
    "follow us",
    "footer",
    "header",
    "homepage",
    "login",
    "menu",
    "more articles",
    "more like this",
    "most read",
    "nav",
    "navigation",
    "newsletter",
    "popular",
    "privacy",
    "recommended",
    "register",
    "related",
    "responses",
    "share",
    "sidebar",
    "sign in",
    "sign up",
    "signup",
    "social",
    "sponsored",
    "subscribe",
    "terms",
    "trending",
]

# Non-content class patterns for scoring penalty
NON_CONTENT_CLASS_PATTERNS: list[str] = [
    "advert",
    "ad-",
    "ads",
    "banner",
    "cookie",
    "copyright",
    "footer",
    "header",
    "homepage",
    "menu",
    "nav",
    "newsletter",
    "popular",
    "privacy",
    "recommended",
    "related",
    "rights",
    "share",
    "sidebar",
    "social",
    "sponsored",
    "subscribe",
    "terms",
    "trending",
    "widget",
]

# Content protection selectors — elements whose presence indicates real content
CONTENT_PROTECTION_SELECTORS: list[str] = [
    "math",
    "[data-mathml]",
    ".katex",
    ".katex-mathml",
    ".katex-display",
    ".MathJax",
    ".MathJax_Display",
    ".MathJax_SVG",
    "mjx-container",
    "pre",
    "code",
    "table",
    "img",
    "picture",
    "video",
    "blockquote",
    "figure",
    'input[type="checkbox"]',  # task lists (GitHub-style)
    "[data-markitai-embed]",  # canonicalized video/social embed links
]

# Elements that are allowed to be empty (void elements)
ALLOWED_EMPTY_ELEMENTS: frozenset[str] = frozenset(
    {
        "area",
        "audio",
        "base",
        "br",
        "col",
        "embed",
        "figure",
        "hr",
        "iframe",
        "img",
        "input",
        "link",
        "meta",
        "object",
        "param",
        "picture",
        "source",
        "svg",
        "td",
        "th",
        "track",
        "video",
        "wbr",
    }
)

# Known code-block languages (ported from defuddle elements/code.ts).
# Language detection patterns are fuzzy (e.g. "(\\w+)-code" matches
# "CodeBlock-code"); a detected token only counts when it names a real
# language.
CODE_LANGUAGES: frozenset[str] = frozenset(
    {
        "abap",
        "actionscript",
        "ada",
        "adoc",
        "agda",
        "antlr4",
        "applescript",
        "arduino",
        "armasm",
        "asciidoc",
        "aspnet",
        "atom",
        "bash",
        "batch",
        "c",
        "clojure",
        "cmake",
        "cobol",
        "coffeescript",
        "cpp",
        "c++",
        "crystal",
        "csharp",
        "cs",
        "css",
        "dart",
        "django",
        "dockerfile",
        "dotnet",
        "elixir",
        "elm",
        "erlang",
        "fish",
        "fortran",
        "fsharp",
        "gdscript",
        "gitignore",
        "glsl",
        "go",
        "golang",
        "gradle",
        "graphql",
        "groovy",
        "haskell",
        "hs",
        "haxe",
        "hlsl",
        "html",
        "idris",
        "ini",
        "java",
        "javascript",
        "js",
        "jsx",
        "jsdoc",
        "json",
        "jsonp",
        "julia",
        "kotlin",
        "latex",
        "lean",
        "lean4",
        "lisp",
        "elisp",
        "livescript",
        "lua",
        "makefile",
        "markdown",
        "md",
        "markup",
        "masm",
        "mathml",
        "matlab",
        "mongodb",
        "mysql",
        "nasm",
        "nginx",
        "nim",
        "nix",
        "objc",
        "ocaml",
        "pascal",
        "perl",
        "php",
        "plaintext",
        "postgresql",
        "powershell",
        "prolog",
        "puppet",
        "python",
        "r",
        "regex",
        "rss",
        "ruby",
        "rb",
        "rust",
        "scala",
        "scheme",
        "scss",
        "shell",
        "sh",
        "solidity",
        "sparql",
        "sql",
        "ssml",
        "svg",
        "swift",
        "tcl",
        "terraform",
        "tex",
        "text",
        "toml",
        "typescript",
        "ts",
        "tsx",
        "unrealscript",
        "verilog",
        "vhdl",
        "vue",
        "webassembly",
        "wasm",
        "xml",
        "yaml",
        "yml",
        "zig",
        "zsh",
    }
)

# Content indicator tokens in class/id for isLikelyContent
CONTENT_INDICATOR_TOKENS: frozenset[str] = frozenset(
    {
        "article",
        "content",
        "entry",
        "image",
        "img",
        "font",
        "figure",
        "figcaption",
        "pre",
        "main",
        "post",
        "story",
        "table",
    }
)

# Inline footnote/citation reference selectors (ported from defuddle
# constants.ts FOOTNOTE_INLINE_REFERENCES).
FOOTNOTE_INLINE_REFERENCES: str = ", ".join(
    [
        "sup.reference",
        "cite.ltx_cite",
        'sup[id^="fnr"]',
        'span[id^="fnr"]',
        'span[class*="footnote_ref"]',
        'span[class*="footnote-ref"]',
        "span.footnote-link",
        "a.citation",
        'a[id^="ref-link"]',
        'a[href^="#fn"]',
        'a[href^="#cite"]',
        'a[href^="#reference"]',
        'a[href^="#footnote"]',
        'a[href^="#r"]',  # Common in academic papers
        'a[href^="#b"]',  # Common for bibliography references
        'a[href*="cite_note"]',
        'a[href*="cite_ref"]',
        "a.footnote-anchor",  # Substack
        "span.footnote-hovercard-target a",  # Substack
        'a[role="doc-biblioref"]',  # Science.org
        'a[id^="fnref"]',
        "sup.footnoteref",  # Wikidot
        "sup.footnote-reference",  # pulldown-cmark / mdBook / zola
        'sup[data-fn] > a[href^="#"]',  # WordPress block editor footnotes
        'sup[id^="ftnt_ref"] a[href^="#ftnt"]',  # Google Docs/Sites
        'span.easy-footnote > a[href^="#easy-footnote-bottom-"]',  # Easy Footnotes WP
        'a.footnote[href^="#"]',  # GNU Texinfo / makeinfo inline markers
        'a[data-type="noteref"]',  # O'Reilly / HTMLBook
    ]
)

# Footnote definition list selectors (ported from defuddle constants.ts
# FOOTNOTE_LIST_SELECTORS).
FOOTNOTE_LIST_SELECTORS: str = ", ".join(
    [
        "div.footnote ol",
        "div.footnotes ol",
        'div[role="doc-endnotes"]',
        'div[role="doc-footnotes"]',
        "ol.footnotes-list",
        "ol.footnotes",
        "ol.references",
        'ol[class*="article-references"]',
        "section.footnotes ol",
        'section[role="doc-endnotes"]',
        'section[role="doc-footnotes"]',
        'section[role="doc-bibliography"]',
        "ul.footnotes-list",
        "ul.ltx_biblist",
        'div.footnote[data-component-name="FootnoteToDOM"]',  # Substack
        "div.footnotes-footer",  # Wikidot
        "div.footnote-definitions",
        "div.footnote-definition",  # pulldown-cmark / mdBook / zola (unwrapped)
        "ol.wp-block-footnotes",  # WordPress block editor footnotes
        "ol.easy-footnotes-wrapper",  # Easy Footnotes WP plugin
        "div.footnotes-segment",  # GNU Texinfo / makeinfo
        "#footnotes",  # standardize_footnotes output container
    ]
)
